<a href="https://colab.research.google.com/github/ajaxrays21/iitkanpur/blob/master/Ajay_Kumar_Indoria_Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lab 1**
1. Use git init to create an empty repo
2. Add a file to local repo and push to github
3. Make additional changes to same file, again push to github
4. Add a collaborator to your repo
5. Ask you collaborator to make change to the file and push to repo
6. You try to make a diff change at the same place in the file and push to repo
7. Step6 will fail, Fix merge conflicts and push again
8. Verify all the commits in github
9. Revert code to previous version


DONE DURING THE SESSION

**Lab 2**
1. Remove push access to master branch from your collabortator
2. Ask your collaborator to create a new branch
3. Push new code changes to that branch
4. Create a pull request from that branch to master branch
5. Approve and merge the pull request
6. Do a git pull and veirfy that you can see the new changes in master branch


DONE DURING THE SESSION

**Lab 3**
1. Use python requests to post a comment on your commit
2. Use python requests to find top 10 commiters on django repo

DONE DURING THE SESSION

In [10]:
import requests
import pprint
headers = {'Authorization': 'token 5ef582f6fa572a416573d30f671250752127c8a2'}
json = {'body':'comment from api call', 'path':'first.html'}
r= requests.post("https://api.github.com/repos/tanushree2k7/tanushree/commits/61760d2a4e85bc6041fa7f4b10aa08d1b34b1247/comments", headers=headers, json=json)
pprint.pprint(r.json())

{'documentation_url': 'https://developer.github.com/v3',
 'message': 'Bad credentials'}


**Lab 4**
1. Create a 8x8x8 array with random values
2. From the matrix in (1) Negate all elements
whose values are between 3 to 8
3. Multiply a 8x3 matrix by 3x2 matrix and
prints the columns as 1 D array

In [0]:
import numpy as np
sampl = np.random.randint(512, size=(8, 8, 8))
sampl



In [0]:
import numpy as np
sampl = np.random.randint(low=3, high=8, size=(8, 8, 8))
sampl

In [0]:
#Multiply a 8x3 matrix by 3x2 matrix and prints the columns as 1 D array
import numpy as np
a = np.random.randint(low=1, high=9, size=(8, 3))
b = np.random.randint(low=1, high=9, size=(3, 2))
c=a.dot(b)
c

**Lab 5**

1. Create a 8x8x8 matrix with random values ranging from 5 to 9
2. Find the diagonal of product of two random 5x5 matrices
3. Negate a boolean, or to change the the sign of the float inplace

Create a 8x8x8 matrix with random values ranging from 5 to 9

In [0]:
import numpy as np
sampl = np.random.randint(low=5, high=9, size=(8, 8, 8))
sampl

Find the diagonal of product of two random 5x5 matrices


In [0]:
import numpy as np
a = np.random.randn(5, 5)
b = np.random.randn(5, 5)
c=a.dot(b)
c.diagonal()

In [0]:
#3. Negate a boolean, or to change the the sign of the float inplace


**Lab 6**

Given 100 random points in 2D space and find the top 10 closest points to the origin.

In [0]:
import numpy
#z=np.random.randn(100,2)
z=np.random.randint(low=0, high=9, size=(100, 2))

def pClosest(points, K): 
   points.sort(key = lambda K: K[0]**2 + K[1]**2) 
   return points[:K] 
points = [[2, 0],
       [2, 8],
       [3, 5],
       [0, 3],
       [5, 1],
       [5, 2],
       [6, 5],
       [6, 0],
       [4, 5],
       [4, 1],
       [5, 7],
       [7, 4],
       [2, 8],
       [7, 0],
       [8, 7],
       [5, 7],
       [3, 0],
       [7, 5],
       [7, 1],
       [7, 4],
       [2, 1],
       [4, 8],
       [3, 4],
       [5, 7],
       [0, 3],
       [1, 3],
       [5, 6],
       [3, 2],
       [3, 7],
       [1, 1],
       [6, 3],
       [2, 8],
       [3, 6],
       [0, 0],
       [2, 5],
       [8, 2],
       [5, 1],
       [5, 1],
       [5, 5],
       [7, 2],
       [3, 5],
       [0, 5],
       [1, 8],
       [5, 5],
       [1, 3],
       [2, 7],
       [2, 5],
       [3, 5],
       [8, 5],
       [8, 7],
       [0, 2],
       [4, 4],
       [6, 3],
       [5, 5],
       [6, 8],
       [2, 4],
       [1, 1],
       [8, 4],
       [8, 3]]
K = 10
print(pClosest(points, K)) 






[[0, 0], [1, 1], [1, 1], [2, 0], [0, 2], [2, 1], [0, 3], [3, 0], [0, 3], [1, 3]]


**Lab 7**

Find the value of pi using Monte Carlo simulation.

**Hint:-** 

Consider a unit circle which is enclosed in a square. randomly genrate uniformily distributed points inside the square. The fraction of points falling inside the circle is pi/4. 

In [0]:
import random as r
import math as m

a = 0
t = 1000
for i in range(0, t):
  x2 = r.random()**2
  y2 = r.random()**2
  if m.sqrt(x2 + y2) < 1.0:
      a += 1
pi = (float(a) / t) * 4
print(pi)

3.1


**Home Work**

1. wap the first two rows of a random 5x5
array
2. How to get the block-sum of a 16x16 matrix
(block size is 4x4)?
3. Sort an array by the nth column
4. Subtract the mean of each row of a matrix
from each element

In [2]:
import numpy as np
z=np.random.rand(5,5)
print(z)
rows = z[:2, :]
print('Rows from Index 1 to 2 :')
print(rows)

[[0.94752792 0.72229096 0.0343781  0.6478254  0.78599523]
 [0.14203981 0.48924204 0.40750138 0.76848206 0.03311188]
 [0.55918168 0.72640228 0.25148448 0.57590425 0.77315365]
 [0.97170495 0.89168969 0.96534399 0.23032209 0.5826985 ]
 [0.16585469 0.19352816 0.9390722  0.85865895 0.05972237]]
Rows from Index 1 to 2 :
[[0.94752792 0.72229096 0.0343781  0.6478254  0.78599523]
 [0.14203981 0.48924204 0.40750138 0.76848206 0.03311188]]


In [5]:
print(rows)

Z = np.ones((16,16))
print(Z)
print("====")
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[0.94752792 0.72229096 0.0343781  0.6478254  0.78599523]
 [0.14203981 0.48924204 0.40750138 0.76848206 0.03311188]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
====
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16

In [6]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print("====")
print(Z[Z[:,1].argsort()])

[[4 9 2]
 [2 1 5]
 [9 6 5]]
====
[[2 1 5]
 [9 6 5]
 [4 9 2]]


In [7]:
X = np.random.rand(4,5)
print(X)
print("======")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.18627108 0.70450061 0.90678901 0.02273609 0.32191724]
 [0.39968478 0.75435903 0.0871051  0.66215092 0.09645167]
 [0.50591643 0.05332027 0.89421457 0.85354851 0.39460999]
 [0.66587888 0.55318296 0.07316325 0.20160909 0.60248354]]
[[-2.42171722e-01  2.76057800e-01  4.78346201e-01 -4.05706714e-01
  -1.06525565e-01]
 [-2.65515167e-04  3.54408727e-01 -3.12845203e-01  2.62200619e-01
  -3.03498628e-01]
 [-3.44055207e-02 -4.87001685e-01  3.53892614e-01  3.13226554e-01
  -1.45711963e-01]
 [ 2.46615333e-01  1.33919420e-01 -3.46100298e-01 -2.17654453e-01
   1.83219998e-01]]
